### ISSUE TITLE
Error 0x80070643 when uninstalling and trying to re-install eduVPN Client

### ISSUE THREAD

**Issue by JsBergbau** [eduvpn/windows#1]
There are several reports for this error 
https://www.windowsphoneinfo.com/threads/error-0x80070643-on-reinstallling-eduvpn.772204/
and 
https://answers.microsoft.com/en-us/windows/forum/all/error-0x80070643-on-reinstallling-eduvpn/63eb385a-ee4a-4e79-b1c9-8af84052d173

I had the same issue with the Let's connect branded version.

Deleting `Let's Connect!` folder in `C:\Program Files\`  worked to reinstall it.

So installer should check if folder exists and probably remove before. Then this error should be gone.

**Comment by ghost** [comment]
Thanks for the report! We are tracking it here: https://github.com/Amebis/eduVPN/issues/205
